import { expect, test } from "@playwright/test";

test("captures, develops, reviews, and records a local publication", async ({ page }) => {
  const response = await page.goto("/");
  await expect(page.getByRole("heading", { name: "Capture the thought. Develop it when it matters." })).toBeVisible();
  expect(page.url()).toMatch(/\/$/);
  expect(response?.headers()["x-content-type-options"]).toBe("nosniff");
  expect(response?.headers()["x-frame-options"]).toBe("DENY");
  expect(response?.headers()["content-security-policy"]).toContain("default-src 'self'");
  await page.getByRole("link", { name: "Editorial Notebook" }).click();
  await expect(page.getByRole("heading", { name: "Editorial Notebook" })).toBeVisible();
  await page.getByLabel("Working notes").fill("# Test notebook\n\nA private working note.");
  await page.getByRole("button", { name: "Save snapshot" }).click();
  await expect(page.getByText(/Snapshot saved at/)).toBeVisible();
  await page.getByRole("link", { name: "Ideas" }).click();
  await page.getByLabel("What are you thinking about?").fill("A rough idea about the missing middle of enterprise AI and why implementation discipline matters.\n\n<style>body{display:none}</style><script>window.__editorialInjected=true</script><a href=\"javascript:alert(1)\">unsafe</a>");
  await page.getByRole("button", { name: "Save to Inbox" }).click();
  await expect(page.getByText("Saved to Inbox. Pick it up whenever you are ready.")).toBeVisible();
  await page.getByRole("link", { name: /A rough idea about the missing middle/i }).first().click();
  await expect(page.getByRole("heading", { name: "Develop the thinking, then the words." })).toBeVisible();
  await expect(page.getByText(/<style>body\{display:none\}/)).toBeVisible();
  expect(await page.evaluate(() => (window as typeof window & { __editorialInjected?: boolean }).__editorialInjected)).toBeUndefined();
  await expect(page.locator('a[href^="javascript:"]')).toHaveCount(0);
  await page.getByRole("button", { name: "Edit title" }).click();
  await page.getByLabel("Working title").fill("The missing middle is operational discipline");
  await page.getByRole("button", { name: "Save title" }).click();
  await expect(page.getByRole("heading", { name: "The missing middle is operational discipline" })).toBeVisible();
  await page.getByRole("button", { name: "Park this idea" }).click();
  await expect(page.getByText(/This idea is parked/)).toBeVisible();
  await page.getByRole("button", { name: "Return to Inbox" }).click();
  await expect(page.getByRole("button", { name: "Develop this idea →" })).toBeVisible();
  await page.getByRole("button", { name: "Move idea down in queue" }).click();
  await page.getByRole("button", { name: "Develop this idea →" }).click();
  await expect(page.getByText("You do not need to answer more questions first.")).toBeVisible();
  await page.getByRole("button", { name: "Continue to editorial review →" }).click();
  await expect(page.getByRole("heading", { name: "Review the thinking before shaping the draft." })).toBeVisible();
  await expect(page.getByRole("navigation", { name: "Idea workflow stages" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Run live editorial review" })).toBeVisible();
  await page.getByText("Advanced run settings").click();
  await expect(page.getByText(/Free local test · \$0\.00 · no provider call/i)).toBeVisible();
  await page.getByRole("button", { name: "Run free deterministic editorial test" }).click();
  await expect(page.getByText("Grounded deterministic test run")).toBeVisible();
  await expect(page.getByText("SUGGESTED CHANGES FOR THIS DRAFT")).toBeVisible();
  await expect(page.getByText("YOUR NEXT ACTION")).toBeVisible();
  await expect(page.getByText("Why the Board suggested this")).toBeVisible();
  await page.getByText(/Grounded with \d+ BOK passages/).click();
  await expect(page.getByText("Selected BOK passages", { exact: true })).toBeVisible();
  await expect(page.getByText("Role and model assignments", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Continue to Write →" }).click();
  await expect(page.getByRole("heading", { name: "Write, review, and prepare each publication output." })).toBeVisible();
  await expect(page.getByText(/Grounded deterministic test output/)).toBeVisible();
  const draft = page.getByLabel("Working draft");
  await expect(draft).toBeVisible();
  await draft.fill("A practical observation about enterprise AI needs a concrete example because operating discipline changes whether a pilot becomes useful. What would change in your organization?");
  await expect(page.getByText(/Unsaved edits are not covered/)).toBeVisible();
  await page.getByRole("button", { name: "Save draft version" }).click();
  await page.getByRole("button", { name: "Run draft review" }).click();
  await expect(page.getByText(/Ready for your final judgment|Revise before publishing/)).toBeVisible();
  await draft.fill("A revised practical observation about enterprise AI needs a concrete example because operating discipline changes whether a pilot becomes useful. What would change in your organization?");
  await expect(page.getByText(/Unsaved edits are not covered/)).toBeVisible();
  await page.getByRole("button", { name: "Save draft version" }).click();
  await page.getByRole("button", { name: "Run draft review" }).click();
  await expect(page.getByText(/Prior review history · 1 saved memo/)).toBeVisible();
  await page.getByText(/Ready for your final judgment|Revise before publishing/).click();
  await page.getByText("Record your decision on the original recommendations").click();
  await page.getByRole("combobox").first().selectOption("revised");
  await expect(page.getByText("Your recommendation decision was saved locally.")).toBeVisible();
  await page.reload();
  await page.getByText(/Ready for your final judgment|Revise before publishing/).click();
  await page.getByText("Record your decision on the original recommendations").click();
  await expect(page.getByRole("combobox").first()).toHaveValue("revised");
  await page.getByText("Visual companion", { exact: true }).click();
  await page.getByRole("button", { name: "Create visual companion" }).click();
  await expect(page.getByText("From a promising pilot to a dependable workflow")).toBeVisible();
  const visualDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download SVG" }).click();
  expect((await visualDownload).suggestedFilename()).toMatch(/draft_\d+_\d{8}T\d{6}.*\.svg$/);
  await page.getByRole("link", { name: "Continue to Finalize →" }).click();
  await expect(page.getByRole("heading", { name: "Confirm the exact versions and record publication." })).toBeVisible();
  await page.getByRole("button", { name: "Check final voice" }).click();
  await expect(page.getByText(/AI-pattern risk/)).toBeVisible();
  await page.getByRole("button", { name: "Mark this version as published" }).click();
  await expect(page.getByText("Published record saved locally.")).toBeVisible();
  await page.getByRole("link", { name: /Write Version/ }).click();
  await expect(page.getByLabel("Working draft")).toBeDisabled();
  await expect(page.getByRole("button", { name: "Save draft version" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Run draft review" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Refresh saved SVG" })).toBeDisabled();
  await page.getByRole("navigation", { name: "Idea workflow stages" }).getByRole("link", { name: /Develop/ }).click();
  await expect(page.getByRole("button", { name: "Edit title" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Move idea up in queue" })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Move idea down in queue" })).toBeDisabled();
  await page.getByRole("navigation", { name: "Idea workflow stages" }).getByRole("link", { name: /Editorial Board/ }).click();
  await expect(page.locator(".run-actions button")).toBeDisabled();
  await page.locator(".live-board-cta > summary").click();
  await page.getByText("Advanced run settings").click();
  await expect(page.getByRole("button", { name: "Run free deterministic editorial test" })).toBeDisabled();
  await page.goto("/content-status");
  await expect(page.getByRole("heading", { name: "Content status" })).toBeVisible();
  await expect(page.getByText("Canonical knowledge base")).toBeVisible();
  const sourceStatus = await page.request.get("/api/content/status?q=enterprise");
  expect(sourceStatus.ok()).toBeTruthy();
  expect((await sourceStatus.json()).bok).toHaveProperty("status");
  const health = await page.request.get("/api/health");
  expect((await health.json()).accessControl).toBe("loopback-only-no-login");
});

test("finalizes Medium and LinkedIn outputs independently from the current canonical article", async ({ page }) => {
  const marker = `e2e-long-form-${Date.now()}`;
  await page.goto("/");
  await page.getByLabel("What are you thinking about?").fill(`${marker}: a detailed article about why enterprise AI pilots need accountable owners before they become dependable workflows.`);
  await page.getByRole("button", { name: "Save to Inbox" }).click();
  await page.getByRole("link", { name: new RegExp(marker) }).click();
  await page.getByRole("button", { name: "Develop this idea →" }).click();
  await page.getByLabel("Publication plan").selectOption("medium_linkedin");
  await page.getByRole("button", { name: "Save development notes" }).click();
  await page.getByRole("button", { name: "Continue to editorial review →" }).click();
  await page.getByText("Advanced run settings").click();
  await page.getByRole("button", { name: "Run free deterministic editorial test" }).click();
  await page.getByRole("navigation", { name: "Idea workflow stages" }).getByRole("link", { name: /Finalize/ }).click();
  await expect(page.getByText(/Create a current LinkedIn companion in Write before recording this article publication/)).toBeVisible();
  await page.getByRole("navigation", { name: "Idea workflow stages" }).getByRole("link", { name: /Write/ }).click();
  await page.getByRole("link", { name: /Write Version/ }).click();
  await expect(page.getByText("Article first, then its LinkedIn companion.")).toBeVisible();
  await page.getByRole("button", { name: /Create LinkedIn version from Article v\d+/ }).click();
  await expect(page.getByText(/LINKEDIN COMPANION · VERSION \d+/)).toBeVisible();
  const draft = page.getByLabel("Working draft");
  await draft.fill("A revised canonical article keeps the operational question clear. It also explains why an accountable owner and a measured outcome matter before teams scale a promising pilot. What would change in your organization?");
  await page.getByRole("button", { name: "Save draft version" }).click();
  await expect(page.getByText(/The LinkedIn companion is stale because article version/)).toBeVisible();
  await page.getByRole("button", { name: /Create a replacement LinkedIn version from Article v\d+/ }).click();
  await page.getByRole("button", { name: "Run draft review" }).click();
  await page.getByRole("button", { name: "Run LinkedIn review" }).click();
  await page.reload();
  await expect(page.getByText("LINKEDIN COMPANION · VERSION", { exact: false })).toBeVisible();
  await page.getByRole("link", { name: "Continue to Finalize →" }).click();
  await expect(page.locator(".finalize-output")).toHaveCount(2);
  await expect(page.locator(".finalize-output").nth(0).locator(".eyebrow").first()).toContainText("MEDIUM ARTICLE");
  await expect(page.locator(".finalize-output").nth(1).locator(".eyebrow").first()).toContainText("LINKEDIN COMPANION");
  await expect(page.getByLabel("Working draft")).toHaveCount(0);
  const voiceButtons = page.getByRole("button", { name: "Check final voice" });
  await voiceButtons.nth(0).click();
  await voiceButtons.nth(1).click();
  const publishButtons = page.getByRole("button", { name: "Mark this version as published" });
  await expect(publishButtons.nth(1)).toBeDisabled();
  await expect(page.getByText(/Record the exact Medium article publication first/)).toBeVisible();
  await publishButtons.nth(0).click();
  await expect(page.getByText("Published record saved locally.")).toBeVisible();
  await page.getByRole("navigation", { name: "Idea workflow stages" }).getByRole("link", { name: /Write/ }).click();
  await expect(page.getByLabel("Working draft")).toBeDisabled();
  const companionEditor = page.getByLabel("LinkedIn companion draft");
  await expect(companionEditor).toBeEnabled();
  await companionEditor.fill("A promising AI pilot still needs an owner, sensible controls, and a measurable outcome before it becomes dependable work. What would you check before scaling it?");
  await page.getByRole("button", { name: "Save LinkedIn version" }).click();
  await page.getByRole("button", { name: "Run LinkedIn review" }).click();
  await page.getByRole("navigation", { name: "Idea workflow stages" }).getByRole("link", { name: /Finalize/ }).click();
  await expect(page.locator(".finalize-output")).toHaveCount(2);
  await page.getByRole("button", { name: "Check final voice" }).click();
  await page.getByRole("button", { name: "Mark this version as published" }).click();
  await expect(page.getByText(/2 of 2 published/)).toBeVisible();
});
