"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { IdeaDetailView, type Detail, type Theme } from "../../queue-client";
import { AppNav } from "../../app-nav";

export function IdeaWorkspaceClient({ ideaId, mode = "develop" }: { ideaId: string; mode?: "develop" | "review" }) {
  const [idea, setIdea] = useState<Detail>(); const [themes, setThemes] = useState<Theme[]>([]); const [note, setNote] = useState(""); const [draft, setDraft] = useState(""); const [answers, setAnswers] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [voiceCheck, setVoiceCheck] = useState<{ riskPercent: number; label: string; findings: Array<{ id: string; severity: string; message: string; suggestion: string }>; disclaimer: string }>();
  async function load() { const [ideaResponse, listResponse] = await Promise.all([fetch(`/api/ideas/${ideaId}`), fetch("/api/ideas")]); const ideaData = await ideaResponse.json() as { idea?: Detail; error?: string }; const listData = await listResponse.json() as { themes: Theme[] }; if (!ideaResponse.ok || !ideaData.idea) throw new Error(ideaData.error ?? "Idea not found."); setIdea(ideaData.idea); setThemes(listData.themes); setDraft(ideaData.idea.draft?.body ?? ""); setAnswers(Object.fromEntries(ideaData.idea.answers.map((answer) => [answer.question, answer.answer]))); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Idea could not be loaded.")); }, 0); return () => window.clearTimeout(timer); // Load the selected local record once.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ideaId]);
  async function request(body: unknown) { const response = await fetch(`/api/ideas/${ideaId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json() as { idea?: Detail; error?: string }; if (!response.ok || !data.idea) throw new Error(data.error ?? "The idea could not be saved."); setIdea(data.idea); setDraft(data.idea.draft?.body ?? draft); return data.idea; }
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (error) { setMessage(error instanceof Error ? error.message : "Something went wrong."); } finally { setBusy(false); } }
  if (!idea) return <main className="queue-shell"><AppNav /><section className="idea-workspace-shell"><Link className="back-link" href="/">← Idea queue</Link><p className="notice">{message || "Loading saved idea…"}</p></section></main>;
  const reviewing = mode === "review";
  async function checkVoice() { await run(async () => { const response = await fetch("/api/voice-check", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: draft }) }); const data = await response.json() as typeof voiceCheck & { error?: string }; if (!response.ok || !data) throw new Error(data.error ?? "The final voice check failed."); setVoiceCheck(data); setMessage("Final human-voice check complete. Review the flagged patterns before publishing."); }); }
  return <main className="queue-shell"><AppNav /><section className="idea-workspace-shell"><header className="idea-workspace-header"><p className="breadcrumbs"><Link href="/">Ideas</Link><span>/</span>{reviewing ? <><Link href={`/ideas/${ideaId}`}>{idea.title}</Link><span>/</span><strong>Editorial Board</strong></> : <strong>{idea.title}</strong>}</p><div><p className="eyebrow">{reviewing ? "Editorial Board" : "Idea workspace"}</p><h1>{reviewing ? "Review the thinking, then shape the draft." : "Develop the thinking, then the words."}</h1></div></header>{message && <p className="notice" role="status">{message}</p>}<section className="detail-panel"><IdeaDetailView idea={idea} themes={themes} note={note} setNote={setNote} setSelected={setIdea} busy={busy} startDeveloping={() => run(async () => { await request({ status: "developing" }); setMessage("Add what you know. The questions below are optional and focused."); })} saveDetails={(event: FormEvent) => { event.preventDefault(); return run(async () => { await request({ title: idea.title, publicationPlan: idea.publicationPlan ?? "linkedin", themeIds: idea.themes.map((theme) => theme.id), note: note || undefined }); setNote(""); setMessage("Details saved locally."); }); }} answers={answers} setAnswers={setAnswers} finishDevelopment={(best) => run(async () => { await request({ action: "develop", useBestJudgment: best, answers: idea.questions.map((question) => ({ question, answer: answers[question] ?? "", choice: best ? "best_judgment" : answers[question]?.trim() ? "answered" : "skipped" })) }); setMessage("Idea is ready for editorial review."); })} board={() => run(async () => { await request({ action: "run_board" }); setMessage("Editorial brief created. Detailed reviews are available below when you want them."); })} draft={draft} setDraft={setDraft} saveDraft={() => run(async () => { await request({ action: "save_draft", body: draft }); setMessage("Draft version saved locally."); })} publish={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); return run(async () => { await request({ action: "publish", platform: form.get("platform"), url: form.get("url"), finalText: draft, title: idea.title, voiceCheckAcknowledged: Boolean(voiceCheck) }); setMessage("Published record saved locally."); }); }} request={request} showDevelopment={!reviewing} showBoard={reviewing} showDraft={reviewing} showPriority={!reviewing} reviewHref={reviewing ? undefined : `/ideas/${ideaId}/review`} voiceCheck={voiceCheck} checkVoice={checkVoice} onDraftChange={() => setVoiceCheck(undefined)} /></section></section></main>;
}
