"use client";

import { useEffect, useState } from "react";
import type { NotebookDocument } from "@/notebook/service";

export function NotebookClient() {
  const [notebook, setNotebook] = useState<NotebookDocument>(); const [content, setContent] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { const response = await fetch("/api/editorial-notebook"); const data = await response.json() as NotebookDocument & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Notebook could not be loaded."); setNotebook(data); setContent(data.content); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Notebook could not be loaded.")); }, 0); return () => window.clearTimeout(timer); // Load the local notebook once.
  }, []);
  async function save() { setSaving(true); setMessage(""); try { const response = await fetch("/api/editorial-notebook", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content }) }); const data = await response.json() as NotebookDocument & { error?: string }; if (!response.ok) throw new Error(data.error ?? "Notebook could not be saved."); setNotebook(data); setContent(data.content); setMessage(`Snapshot saved at ${new Date(data.updatedAt).toLocaleString()}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Notebook could not be saved."); } finally { setSaving(false); } }
  return <main className="notebook-page"><header className="notebook-header"><div><p className="eyebrow">Local working document</p><h1>Editorial Notebook</h1><p>Capture evolving observations, questions, and post angles. This is separate from the canonical BOK.</p></div><button disabled={saving || !notebook} onClick={() => void save()}>{saving ? "Saving…" : "Save snapshot"}</button></header>{message && <p className="notice" role="status">{message}</p>}<div className="notebook-layout"><section><label className="notebook-editor-label" htmlFor="notebook">Working notes</label><textarea id="notebook" className="notebook-editor" value={content} onChange={(event) => setContent(event.target.value)} placeholder="Loading local notebook…" disabled={!notebook} maxLength={200_000} /></section><aside className="notebook-info"><p className="eyebrow">HOW IT WORKS</p><p>Save creates an immutable timestamped Markdown version and updates the latest working copy.</p><dl><div><dt>Latest file</dt><dd className="path-value">{notebook?.path ?? "Loading…"}</dd></div><div><dt>Last saved</dt><dd>{notebook ? new Date(notebook.updatedAt).toLocaleString() : "Loading…"}</dd></div><div><dt>Snapshots</dt><dd>{notebook?.versions.length ?? 0}</dd></div></dl><p className="notebook-note">Future phases will add version browse, comparison, restore, and sending a candidate post directly to the Idea Queue.</p></aside></div></main>;
}
