"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Brief = { id: string; version: number; status: string; workingTitle?: string | null; centralThesis?: string | null; intendedAudience?: string | null; purpose?: string | null; triggerContext?: string | null; supportingPoints: string[]; userProvidedEvidence: string[]; claimsRequiringValidation: string[]; possibleCounterargument?: string | null; desiredTone?: string | null; intendedPlatform?: string | null; suggestedLength?: string | null; relationshipToPreviousPosts?: string | null; openQuestions: string[]; systemAssumptions: string[] };
type Workspace = { id: string; rawNotes: string; existingDraft: string; status: string; questions: string[]; answers: Array<{ question: string; answer: string; choice: string }>; brief?: Brief; selectedPath?: string };
type BoardResult = { runId: string; status: string; provider: string; model: string; estimatedCost: number; actualCost: number; reviews: Array<{ id: string; role: string; summary: string; confidence: number; recommendations: Array<{ id: string; text: string; decision?: string }> }>; synthesis?: { summary: string; disagreements: string[] }; context: Array<{ headingPath: string; sourceLocation: string; text: string }> };
type BriefForm = Record<string, string>;

const fields: Array<[keyof Brief, string, "input" | "textarea"]> = [["workingTitle", "Working title", "input"], ["centralThesis", "Central thesis", "textarea"], ["intendedAudience", "Intended audience", "input"], ["purpose", "Purpose", "textarea"], ["triggerContext", "Trigger or context", "textarea"], ["possibleCounterargument", "Possible counterargument", "textarea"], ["relationshipToPreviousPosts", "Relationship to previous posts", "textarea"]];
const listFields: Array<[keyof Brief, string]> = [["supportingPoints", "Supporting points"], ["userProvidedEvidence", "User-provided evidence"], ["claimsRequiringValidation", "Claims requiring validation"], ["openQuestions", "Open questions"], ["systemAssumptions", "System assumptions"]];
const toneOptions = ["Direct", "Thoughtful", "Conversational", "Provocative", "Optimistic", "Analytical", "Practical", "Warm"];
const platformOptions = ["LinkedIn post", "Newsletter", "Personal blog", "Company blog", "Internal memo", "Presentation script"];
const lengthOptions = ["Under 1,300 characters", "300–500 words", "500–800 words", "800–1,200 words", "1,200–1,800 words"];

function briefToForm(brief: Brief): BriefForm { return Object.fromEntries([...fields.map(([key]) => [key, String(brief[key] ?? "")]), ...listFields.map(([key]) => [key, (brief[key] as string[]).join("\n")])]); }
function errorText(error: unknown) { return error instanceof Error ? error.message : "Something went wrong. Please try again."; }

export function WorkspaceClient() {
  const [workspace, setWorkspace] = useState<Workspace>();
  const [notes, setNotes] = useState(""); const [existingDraft, setExistingDraft] = useState("");
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [briefForm, setBriefForm] = useState<BriefForm>({});
  const [board, setBoard] = useState<BoardResult>();
  const [saved, setSaved] = useState<Array<{ id: string; title: string; status: string; updated_at: string }>>([]);
  const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const ideaId = useMemo(() => typeof window === "undefined" ? "" : new URLSearchParams(window.location.search).get("idea") ?? "", []);

  useEffect(() => { fetch("/api/intake").then((response) => response.json()).then((data: { items: typeof saved }) => setSaved(data.items)); if (!ideaId) return; fetch(`/api/intake/${ideaId}`).then(async (response) => response.ok ? response.json() : Promise.reject(new Error("This saved workspace could not be found."))).then((data: Workspace) => { setWorkspace(data); if (data.brief) setBriefForm(briefToForm(data.brief)); }).catch((error: unknown) => setMessage(errorText(error))); }, [ideaId]);

  async function request(url: string, body?: unknown) { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json() as Workspace & { error?: string }; if (!response.ok) throw new Error(data.error ?? "The local workspace could not be updated."); return data; }
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setMessage(""); try { const data = await request("/api/intake", { rawNotes: notes, existingDraft }); const created = data as unknown as { id: string }; window.history.replaceState(null, "", `/dashboard?idea=${encodeURIComponent(created.id)}`); const loaded = await fetch(`/api/intake/${created.id}`).then((response) => response.json()) as Workspace; setWorkspace(loaded); setSaved((items) => [{ id: created.id, title: notes.slice(0, 100), status: "clarifying", updated_at: new Date().toISOString() }, ...items]); setMessage("Your idea is saved. Answer what is useful, skip what is not, or use best judgment."); } catch (error) { setMessage(errorText(error)); } finally { setLoading(false); } }
  async function complete(useBestJudgment: boolean) { if (!workspace) return; setLoading(true); setMessage(""); try { const payload = { action: "complete", useBestJudgment, answers: workspace.questions.map((question) => ({ question, answer: answers[question] ?? "", choice: useBestJudgment ? "best_judgment" : (answers[question]?.trim() ? "answered" : "skipped") })) }; const data = await request(`/api/intake/${workspace.id}`, payload); setWorkspace(data); setBriefForm(briefToForm(data.brief!)); setMessage("Your editable Content Intent Brief is ready."); } catch (error) { setMessage(errorText(error)); } finally { setLoading(false); } }
  async function saveBrief(event?: { preventDefault(): void }) { event?.preventDefault(); if (!workspace) return; setLoading(true); setMessage(""); try { const brief = Object.fromEntries([...fields.map(([key]) => [key, briefForm[key] || null]), ...listFields.map(([key]) => [key, (briefForm[key] ?? "").split("\n").map((item) => item.trim()).filter(Boolean)])]); const data = await request(`/api/intake/${workspace.id}`, { action: "update_brief", brief }); setWorkspace(data); setBriefForm(briefToForm(data.brief!)); setMessage(`Brief version ${data.brief?.version} saved locally.`); } catch (error) { setMessage(errorText(error)); } finally { setLoading(false); } }
  async function choosePath(path: "review_existing_draft" | "create_working_draft" | "review_idea") { if (!workspace) return; setLoading(true); try { const data = await request(`/api/intake/${workspace.id}`, { action: "choose_path", path }); setWorkspace(data); setMessage(path === "review_existing_draft" ? "Your original draft is preserved. Editorial review is the next milestone." : "Your path is saved. Editorial execution begins in the next milestone."); } catch (error) { setMessage(errorText(error)); } finally { setLoading(false); } }
  async function runBoard() { if (!workspace) return; setLoading(true); setMessage(""); try { const response = await fetch(`/api/board/${workspace.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ budgetCap: 0 }) }); const data = await response.json() as BoardResult & { error?: string }; if (!response.ok) throw new Error(data.error); setBoard(data); setMessage(`Editorial Board completed with ${data.provider} / ${data.model}. Estimated and actual cost: $${data.actualCost.toFixed(2)}.`); } catch (error) { setMessage(errorText(error)); } finally { setLoading(false); } }
  async function decide(recommendationId: string, decision: "accepted" | "partially_accepted" | "rejected") { if (!workspace) return; await fetch(`/api/board/${workspace.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "decide", recommendationId, decision }) }); setBoard(board ? { ...board, reviews: board.reviews.map((review) => ({ ...review, recommendations: review.recommendations.map((recommendation) => recommendation.id === recommendationId ? { ...recommendation, decision } : recommendation) })) } : undefined); }
  function toggleTone(tone: string) { const selected = new Set((briefForm.desiredTone ?? "").split(",").map((item) => item.trim()).filter(Boolean)); if (selected.has(tone)) selected.delete(tone); else selected.add(tone); setBriefForm({ ...briefForm, desiredTone: [...selected].join(", ") }); }

  return <main className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark">A</span><span>AI Editorial<br />Board</span></a><nav><a className="nav-link active" href="/">⌂ Workspace</a><a className="nav-link" href="/content-status">◈ Content status</a></nav><div className="saved-work"><strong>Saved work</strong>{saved.map((item) => <a key={item.id} href={`/?idea=${item.id}`}><span>{item.title}</span><small>{item.status.replaceAll("_", " ")}</small></a>)}</div></aside><section className="workspace intake-workspace"><header className="topbar"><div><p className="eyebrow">Editorial workspace</p><h1>{workspace?.brief ? "Shape the work before the words." : "Start with the idea, not the format."}</h1></div></header>{message && <p className="workspace-message">{message}</p>}{!workspace && <form className="idea-form" onSubmit={create}><h2>What are you thinking about?</h2><textarea value={notes} onChange={(event) => setNotes(event.target.value)} minLength={3} required /><button>Continue to clarification →</button></form>}{workspace && !workspace.brief && <section className="clarification-panel"><h2>A few focused questions.</h2>{workspace.questions.map((question) => <label key={question}>{question}<textarea value={answers[question] ?? ""} onChange={(event) => setAnswers({ ...answers, [question]: event.target.value })} /></label>)}<button onClick={() => complete(false)}>Create my brief</button><button onClick={() => complete(true)}>Use your best judgment</button></section>}{workspace?.brief && <section className="brief-editor"><h2>Content Intent Brief · Version {workspace.brief.version}</h2><label>Working title<input value={briefForm.workingTitle ?? ""} onChange={(event) => setBriefForm({ ...briefForm, workingTitle: event.target.value })} /></label><label>Central thesis<textarea value={briefForm.centralThesis ?? ""} onChange={(event) => setBriefForm({ ...briefForm, centralThesis: event.target.value })} /></label><button onClick={saveBrief}>Save new version</button><section className="path-chooser"><h2>Choose a path</h2><button onClick={() => choosePath("review_existing_draft")} disabled={!workspace.existingDraft}>Review existing draft</button><button onClick={() => choosePath("create_working_draft")}>Create working draft</button><button onClick={() => choosePath("review_idea")}>Review idea first</button></section>{workspace.selectedPath && <section className="board-panel"><h2>Editorial Board</h2><button onClick={runBoard}>Run Editorial Board</button>{board?.reviews.map((review) => <article key={review.id}><h3>{review.role}</h3><p>{review.summary}</p></article>)}</section>}</section>}</section></main>;
}
